name: Build API Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'api/**'
      - '.github/workflows/build-api-docker.yml'
  workflow_dispatch:

jobs:
  build-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-api:latest
          platforms: linux/amd64,linux/arm64
