name: Delete All Caches

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of all cache keys"
          cacheKeys=$(gh cache list --limit 100 --json id --jq '.[].id')

          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              echo "Deleting cache with key: $cacheKey"
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
