name: Delete All Caches

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup all caches in batches
        run: |
          set +e
          while true; do
            cacheKeys=$(gh cache list --limit 100 --json id --jq '.[].id')
            if [ -z "$cacheKeys" ]; then
              echo "No more caches to delete."
              break
            fi
            echo "Deleting caches..."
            for cacheKey in $cacheKeys; do
              gh cache delete $cacheKey
            done
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
