name: Publish Stable Docker Images

on:
  workflow_dispatch:

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Pull latest app image (amd64)
        run: docker pull --platform linux/amd64 ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-app:latest

      - name: Pull latest app image (arm64)
        run: docker pull --platform linux/arm64 ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-app:latest

      - name: Pull latest api image (amd64)
        run: docker pull --platform linux/amd64 ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-api:latest

      - name: Pull latest api image (arm64)
        run: docker pull --platform linux/arm64 ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-api:latest

      - name: Tag app image as stable
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-app:stable

      - name: Tag api image as stable
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-api:stable

      - name: Push stable app image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-app:stable

      - name: Push stable api image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/train-dashboard-api:stable
