name: Test API
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/test-api.yml"
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate cache keys
        id: cache_keys
        working-directory: api
        run: |
          echo "python_dependencies_cache_key=CI-test-and-python-dependencies-$(sha256sum requirements.txt | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: ls
        working-directory: api
        run: |
          ls -la



      # - name: Restore cached python venv
      #   id: venv_cache
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: |
      #       **/venv
      #     key: ${{ env.python_dependencies_cache_key }}

      # - name: Install dependencies
      #   working-directory: api
      #   if: steps.venv_cache.outputs.cache-hit != 'true'
      #   run: |
      #     python -m venv venv
      #     . venv/bin/activate
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Cache python dependencies
      #   if: steps.venv_cache.outputs.cache-hit != 'true'
      #   uses: actions/cache/save@v4
      #   with:
      #     path: |
      #       **/venv
      #     key: ${{ env.python_dependencies_cache_key }}

      # - name: Run tests
      #   working-directory: api
      #   run: |
      #     pytest
