name: Test APP
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - ".github/workflows/test-app.yml"
  workflow_dispatch:

jobs:
  test-app:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Generate cache keys
        id: cache_keys
        working-directory: app
        run: |
          echo "npm_dependencies_cache_key=CI-test-and-build-npm-dependencies-$(sha256sum pnpm-lock.yaml | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Restore cached npm dependencies
        id: cache_dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            **/node_modules
          key: ${{ env.npm_dependencies_cache_key }}

      - name: install dependencies
        working-directory: app
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Cache npm dependencies
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            **/node_modules
          key: ${{ env.npm_dependencies_cache_key }}

      - name: Run unit tests
        working-directory: app
        run: pnpm test
